---
- name: 'create file and enter content'
  hosts: node01
  become: true
  tasks:
          - copy:
                  dest: /opt/file.txt
                  content: "This file is created by Ansible!"